### ISSUE TITLE
Remove a line from README

### ISSUE THREAD

**Issue by nikssardana** [nikssardana/gdriveTorrent#21]
Remove the line 
> Remove dependency on path (/nikhil/Programs...) to allow the application to run in any directory

The dependency on this path has been removed. Also, install.sh clones the project into appropriate folder by itself, so no need of this line in documentation.

**Comment by coderaavan** [comment]
Let me take this issue please.

**Comment by nikssardana** [comment]
Sure @coderaavan, go ahead!
