### ISSUE TITLE
One click deploy

### ISSUE THREAD

**Issue by nikssardana** [nikssardana/gdriveTorrent#7]
Current method to deploy on a system is inefficient and requires a lot of steps. Devise a better method to deploy the application on a server (maybe on heroku or something else)?

**Comment by anestv** [comment]
> cd into the cloned folder. Add executable permissions to downloaded.py file by typing: sudo chmod +x downloaded.py Initialise the gdrive utility by typing: gdrive init Open the url specified in gdrive and give appropriate permissions. Then, copy the access token from your browser and paste it into the terminal. Create database: Env/bin/python gdriveTorrent/manage.py migrate Create a superuser: Env/bin/python gdriveTorrent/manage.py createsuperuser Run the django development server: Env/bin/python gdriveTorrent/manage.py runserver 0.0.0.0:8000 Open the url: localhost:8000 in your browser and login with the admin credentials you just created.

**Comment by anestv** [comment]
> cd into the cloned folder. Add executable permissions to downloaded.py file by typing: sudo chmod +x downloaded.py Initialise the gdrive utility by typing: gdrive init Open the url specified in gdrive and give appropriate permissions. Then, copy the access token from your browser and paste it into the terminal. Create database: Env/bin/python gdriveTorrent/manage.py migrate Create a superuser: Env/bin/python gdriveTorrent/manage.py createsuperuser Run the django development server: Env/bin/python gdriveTorrent/manage.py runserver 0.0.0.0:8000 Open the url: localhost:8000 in your browser and login with the admin credentials you just created.

I'm thinking that some of these steps could be put in a script file.

I have a question though: is the user supposed to run `gdrive init`? Where is the command `gdrive` located? Or am I missing something?

**Comment by nikssardana** [comment]
Hey @anestv 
Thanks for your interest!
+1 for the script idea.
gdrive is actually a utility that lets you access your google drive via command line.
You can get it here:
https://github.com/prasmussen/gdrive

**Comment by circa10a** [comment]
Why was this reopened?

**Comment by nikssardana** [comment]
@circa10a the changes in README were left. I thought maybe some beginner contributor may add it.
Since you already added the Easy Install steps, it can be closed now.
